#!/bin/bash
echo "=== DuckDNS Setup untuk SSH External Access ==="
echo ""
echo "1. Buka https://www.duckdns.org di browser"
echo "2. Login dengan Google/GitHub account"
echo "3. Buat subdomain baru (misal: galyarder.duckdns.org)"
echo "4. Copy token yang diberikan"
echo ""
echo "5. Kemudian jalankan command ini (ganti YOUR_SUBDOMAIN dan YOUR_TOKEN):"
echo ""
echo "sudo tee /etc/systemd/system/duckdns.service << 'EOFSVC'"
echo "[Unit]"
echo "Description=DuckDNS IP updater"
echo ""
echo "[Service]"
echo "Type=oneshot"
echo "ExecStart=/usr/bin/curl -fsS 'https://www.duckdns.org/update?domains=YOUR_SUBDOMAIN&token=YOUR_TOKEN&ip='"
echo "EOFSVC"
echo ""
echo "sudo tee /etc/systemd/system/duckdns.timer << 'EOFTIMER'"
echo "[Unit]"
echo "Description=Run DuckDNS updater every 5 minutes"
echo ""
echo "[Timer]"
echo "OnBootSec=1min"
echo "OnUnitActiveSec=5min"
echo "Unit=duckdns.service"
echo ""
echo "[Install]"
echo "WantedBy=timers.target"
echo "EOFTIMER"
echo ""
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable --now duckdns.timer"
echo ""
echo "# Test setelah beberapa menit:"
echo "nslookup YOUR_SUBDOMAIN.duckdns.org"
