#!/usr/bin/env bash
# Manual Verification Commands
# Copy-paste command yang lu mau untuk cek manual

echo "======================================"
echo "MANUAL VERIFICATION COMMANDS"
echo "======================================"
echo ""

echo "1. FINGERPRINT STATUS"
echo "   Check if enabled/disabled:"
echo "   systemctl is-enabled fprintd.service"
echo "   systemctl is-active fprintd.service"
echo ""
echo "   Expected desktop mode: masked + inactive"
echo "   Expected laptop mode: enabled + active"
echo ""

echo "2. TOUCHPAD STATUS"
echo "   Check if enabled/disabled:"
echo "   gsettings get org.gnome.desktop.peripherals.touchpad send-events"
echo ""
echo "   Expected desktop mode: 'disabled'"
echo "   Expected laptop mode: 'enabled'"
echo ""

echo "3. CPU LIMIT (Max Performance %)"
echo "   Check CPU cap:"
echo "   cat /sys/devices/system/cpu/intel_pstate/max_perf_pct"
echo ""
echo "   Expected both modes: 100 (no limit!)"
echo ""

echo "4. TURBO BOOST"
echo "   Check if turbo enabled:"
echo "   cat /sys/devices/system/cpu/intel_pstate/no_turbo"
echo ""
echo "   Expected: 0 = enabled, 1 = disabled"
echo "   Expected both modes: 0 (enabled)"
echo ""

echo "5. PLATFORM PROFILE"
echo "   Check power profile:"
echo "   cat /sys/firmware/acpi/platform_profile"
echo ""
echo "   Available options:"
echo "   cat /sys/firmware/acpi/platform_profile_choices"
echo ""
echo "   Expected desktop mode: performance"
echo "   Expected laptop mode: balanced"
echo ""

echo "6. CPU GOVERNOR"
echo "   Check CPU governor (optional):"
echo "   cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
echo ""
echo "   Common values: powersave, performance, schedutil"
echo ""

echo "7. WiFi POWER SAVE"
echo "   Check WiFi interface:"
echo "   iw dev"
echo ""
echo "   Check power save status:"
echo "   iw dev wlan0 get power_save"
echo "   (replace wlan0 with your interface name)"
echo ""
echo "   Expected both modes: Power save: off"
echo ""

echo "8. USB AUTOSUSPEND"
echo "   Count total USB devices:"
echo "   find /sys/bus/usb/devices/*/power/control -type f 2>/dev/null | wc -l"
echo ""
echo "   Count devices with autosuspend OFF:"
echo "   grep -l \"on\" /sys/bus/usb/devices/*/power/control 2>/dev/null | wc -l"
echo ""
echo "   List all USB devices and their status:"
echo "   for d in /sys/bus/usb/devices/*/power/control; do dir=\$(dirname \"\$d\"); product=\$(cat \"\$dir/product\" 2>/dev/null || echo \"Unknown\"); control=\$(cat \"\$d\"); echo \"- \$product: \$control\"; done"
echo ""
echo "   Expected both modes: all devices = 'on' (autosuspend OFF)"
echo ""

echo "9. BATTERY THRESHOLDS"
echo "   Check battery charge limits:"
echo "   cat /sys/class/power_supply/BAT0/charge_control_start_threshold"
echo "   cat /sys/class/power_supply/BAT0/charge_control_end_threshold"
echo ""
echo "   Expected: Controlled by GNOME Settings (not scripts)"
echo "   Current: 0-100 or your custom setting"
echo ""

echo "10. CURRENT MODE STATE"
echo "   Check which mode is active:"
echo "   cat ~/.config/mode-switcher.state"
echo ""
echo "   Shows: MODE=desktop or MODE=laptop + timestamp"
echo ""

echo "======================================"
echo "QUICK ALL-IN-ONE CHECK"
echo "======================================"
echo ""
echo "Run this for complete status:"
cat << 'QUICKCHECK'
echo "Fingerprint: $(systemctl is-enabled fprintd.service 2>&1 | head -1) / $(systemctl is-active fprintd.service 2>&1 | head -1)"
echo "Touchpad: $(gsettings get org.gnome.desktop.peripherals.touchpad send-events)"
echo "CPU Cap: $(cat /sys/devices/system/cpu/intel_pstate/max_perf_pct)%"
echo "Turbo: $(cat /sys/devices/system/cpu/intel_pstate/no_turbo) (0=enabled, 1=disabled)"
echo "Platform: $(cat /sys/firmware/acpi/platform_profile)"
echo "WiFi: $(iw dev $(iw dev | awk '$1=="Interface"{print $2; exit}') get power_save 2>/dev/null)"
echo "USB Autosuspend: $(grep -l "on" /sys/bus/usb/devices/*/power/control 2>/dev/null | wc -l)/$(find /sys/bus/usb/devices/*/power/control -type f 2>/dev/null | wc -l) devices OFF"
echo "Battery: $(cat /sys/class/power_supply/BAT0/charge_control_start_threshold)-$(cat /sys/class/power_supply/BAT0/charge_control_end_threshold)%"
QUICKCHECK
echo ""

echo "======================================"
echo "COPY COMMANDS ABOVE AS NEEDED!"
echo "======================================"
